### ISSUE TITLE
Build failed in Raspbian Stretch

### ISSUE THREAD

**Issue by aytekno** [fstl-app/fstl#24]
Hello,
make -j8 command fails after %46 of build on Raspberry pi 3. What can be the reason?
Thank you.

**Comment by Akranen** [comment]
Hi,

A screenshot of the error message can help.

Thanks

**Comment by aytekno** [comment]
Thank you. Build completed with the command make -j4. But again program can not be opened with ./fstl command. Gives the following error: 
![screenshot_1](https://user-images.githubusercontent.com/19725045/34518157-38f1512a-f08f-11e7-9ee9-a50b338a19ef.png)

**Comment by mkeeter** [comment]
[This bug](https://bugreports.qt.io/browse/QTBUG-46301) looks relevant.  Can you poke around in [context creation](https://github.com/mkeeter/fstl/blob/master/src/window.cpp#L29-L30) and see whether anything changes?

`fstl` also uses `QGL*` classes, rather than the more modern `QOpenGL*` classes; if you open up a PR that fixes this I'll happily merge it in.

**Comment by DeveloperPaul123** [comment]
[This](https://gist.github.com/jeffcogswell/62395900725acef1c0a5a608f7eb7a05) may also fix the warning about the accessibility bus address; but it might be a band-aid fix.

**Comment by DeveloperPaul123** [comment]
@aytekno Any updates on this?

**Comment by DeveloperPaul123** [comment]
Closing this as a stale issue
