### ISSUE TITLE
Corrupted stl with libfivepy

### ISSUE THREAD

**Issue by rcmz** [fstl-app/fstl#37]
If you open an [libfivepy](https://gitlab.com/rcmz0/libfivepy) generated stl file with fstl and set it to auto-reload; every time you regenerate the stl (with libfivepy) fstl say it is corrupted. Which is strange because it display the stl fine and it doesn't occur when you load the file manually.

This is probably a libfivepy issue but here is a post anyway.

Link to the thread on libfivepy: https://gitlab.com/rcmz0/libfivepy/issues/4

**Comment by mkeeter** [comment]
What's the precise error message?

I wonder if this is caused by it trying to read the STL while the library is partway through writing it.

**Comment by DeveloperPaul123** [comment]
That was my thought as well; although the `fileChanged` signal from the `QFileSystemWatcher` shouldn't be emitted until after the file is modified. That should be after writing is done right?

**Comment by rcmz** [comment]
That's what I thought too, but I did some testing and it doesn't appear to be the case. I could be wrong thought.

The error message is : `Window::on_bad_stl()`

**Comment by DeveloperPaul123** [comment]
@rcmz Would you be willing to share the python code your using to cause the issue to occur?

**Comment by rcmz** [comment]
Sure, the python code is just a wrapper around [`libfive.h`.](https://github.com/libfive/libfive)

Here is a important bit :
```python
def save_mesh(self, region, resolution, file_name):
        return libfive.libfive_tree_save_mesh(self.ptr, region, resolution, str.encode(file_name))
```

The full code is available at https://gitlab.com/rcmz0/libfivepy/blob/master/libfive/kernel.py

**Comment by mkeeter** [comment]
One easy thing to check – if you try to re-open the file in fstl (instead of autoreloading), does it still show that error?  This will tell you if the problem is in the STL or in the autoloading process.

**Comment by SlipperyPete** [comment]
I too am having this issue, Compiling STL's from OpenSCAD. FSTL is popping up with this error about half a second before my console says it's finished. Then FSTL reloads the file perfectly simultaneous with the console finishing, Off the top of my head either reloading on the second `fileChanged` or adding a delay could jerry-rig it for these situations, but both rely on either what is potentially essentially a glitch in the other program or an arbitrary number that could easily be too small or too large for any given file.

Perhaps in lieu of a real solution a toggle for my first suggestion could help for the time being. (Assuming of course the file reloading properly is because it retriggers the `fileChanged` and isn't just a delayed reaction)

**Comment by DanielJoyce** [comment]
It needs to write to a tempfile first, then rename it to the file fstl is loading. Thats the only way to be atomic.
